### ISSUE TITLE
Stop pushing to Docker on every master change

### ISSUE THREAD

**Issue by rarkins** [renovatebot/docker-base#35]
Example of where we released unnecessarily: https://github.com/renovatebot/docker-base/runs/521836180

**Comment by rarkins** [comment]
Is this where the caching is broken? https://github.com/renovatebot/docker-base/runs/521836180#step:5:116

**Comment by viceice** [comment]
Hopefully with latest changes this will not happen again

**Comment by viceice** [comment]
fixed, latest to releases produced: `latest: digest: sha256:d694b03ba0df63ac9b27445e76657d4ed62898d721b997372aab150ee84e07a1 size: 3030` 💪

**Comment by rarkins** [comment]
![image](https://user-images.githubusercontent.com/6311784/77173945-9e47eb80-6ac0-11ea-9637-5a599627b3f8.png)

**Comment by viceice** [comment]
yes, but it's the same digest as before

**Comment by viceice** [comment]
![image](https://user-images.githubusercontent.com/1798109/77174302-23330500-6ac1-11ea-820d-7631f686470f.png)

One hour ago, same digest

**Comment by rarkins** [comment]
Any way we can stop it triggering the "last updated" though? I don't think that's sustainable for us across all of these images because makes it near impossible to know when it *really* was last changed.

**Comment by viceice** [comment]
maybe i can find a method to check latest tag before push
